from typing import Dict, Tuple
from src.models.cell import Cell
from PyQt6.QtGui import QImage

class Automaton:
    py_cell: Cell

    def __init__(self, size: Tuple[int, int], py_cell: Cell, img_ptr: int, img_bytes:int, frame_time: float) -> None: ...
    def print_state(self) -> None: ...
    def update_grid(self, if_charged: bool) -> None: ...
    def to_cell_data(self) -> int: ...#Tuple[int, Dict[Tuple[int, int], Dict]]: ...
    def recreate_from_dict(self, vals) -> None: ...
    def get_frame_time(self) -> float: ...
    def set_frame_time(self, frame_time: float) -> None: ...
    def get_shape(self) -> Tuple[int, int]: ...
    def get_cell_data(self, position: Tuple[int, int]) -> Dict: ...
    def get_buffer_size(self) -> int: ...
    def render_frame(self, idx: int, if_charged: bool) -> int: ...
    def modify_cell_state(self, coords: set[tuple[int, int]], new_state: CellState) -> None: ...
    def commit_current_automaton(self) -> None: ...
    def undo_modification(self) -> None: ...

