from typing import Dict, Tuple
from src.models.cell import Cell

class Automaton:
    py_cell: Cell

    def __init__(self, py_cell: Cell) -> None: ...
    def print_state(self) -> None: ...
    def update_grid(self) -> None: ...
    def to_cell_data(self) -> Tuple[int, Dict[Tuple[int, int], Dict]]: ...
    def recreate_from_dict(self, vals) -> None: ...
    def get_frame_time(self) -> float: ...
    def set_frame_time(self, frame_time: float) -> None: ...
    def get_shape(self) -> Tuple[int, int]: ...
